#! /bin/sh
#
# Brother Print filter
# Copyright (C) 2005-2006 Brother. Industries, Ltd.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
#

if [ "$1" = '-e' ]; then
  lpadmin -x PT-9500PC
  rm -f /usr/share/cups/model/brpt9500pc.ppd
  rm -f /usr/lib/cups/backend/brusb_pt9500pc
  rm -f /usr/lib64/cups/backend/brusb_pt9500pc
  rm -f /usr/lib/cups/filter/brlpdwrapperpt9500pc
  rm -f /usr/lib64/cups/filter/brlpdwrapperpt9500pc
  rm -f /usr/local/Brother/PTouch/pt9500pc/cupswrapper/brcupsconfpt1
if [  -e /etc/init.d/cups ]; then
   /etc/init.d/cups restart
elif [  -e /etc/init.d/cupsys ]; then
   /etc/init.d/cupsys restart
fi
#  /etc/init.d/cups restart
  exit 0
fi
if [ "$1" = "-r" ]; then
  lpadmin -x PT-9500PC
if [  -e /etc/init.d/cups ]; then
   /etc/init.d/cups restart
elif [  -e /etc/init.d/cupsys ]; then
   /etc/init.d/cupsys restart
fi
#  /etc/init.d/cups restart
  exit 0
fi
if [ "$1" = "help" ] || [ "$1" = "-h" ]; then
  echo   'option -h : help'
  echo   '       -i : install'
  echo   '       -e : uninstall'
  echo   '       -r : remove printer'
  exit 0
fi
#mkdir -p /usr/local/Brother/PTouch/pt9500pc/filter
#mkdir -p /usr/lib/cups/filter

if [ -e "/usr/local/Brother/PTouch/pt9500pc/lpd/filterpt9500pc" ]; then
  :
else
  echo "ERROR : Brother LPD filter is not installed."
fi
rm -f /usr/share/cups/model/brpt9500pc.ppd
ppd_file_name=/usr/share/cups/model/brpt9500pc.ppd

cat <<ENDOFPPDFILE >$ppd_file_name
*PPD-Adobe: "4.3"

*%================================================
*%	Copyright(C) 2006 Brother Industries, Ltd.
*%	"Brother PT-9500PC CUPS"
*%================================================

*%==== General Information Keywords ========================
*FormatVersion: "4.3"
*FileVersion: "1.00"
*LanguageVersion: English
*LanguageEncoding: ISOLatin1
*PCFileName: "PT9500PC.PPD"
*Manufacturer: "Brother"
*Product: "(PT-9500PC)"
*1284DeviceID: "MFG: Brother;MDL: PT-9500PC"
*cupsVersion: 1.1


*cupsManualCopies: False
*cupsFilter: "application/vnd.cups-postscript 0 brlpdwrapperpt9500pc"
*cupsModelNumber: 1
*ModelName: "Brother PT-9500PC"
*ShortNickName: "Brother PT-9500PC"
*NickName: "Brother PT-9500PC CUPS v1.1"
*PSVersion: "(3010.106) 3"

*%==== Basic Device Capabilities =============
*LanguageLevel: "3"
*ColorDevice: False
*DefaultColorSpace: Gray
*FileSystem: False
*Throughput: "12"
*LandscapeOrientation: Plus90
*VariablePaperSize: False
*TTRasterizer: Type42
*FreeVM: "1700000"

*%DefaultOutputOrder: Reverse

*%==== Media Selection ======================
*OpenUI *PageSize/Media Size: PickOne
*OrderDependency: 11 AnySetup *PageSize
*DefaultPageSize: brS36mm
*PageSize brS6mm/1/4":						"          "
*PageSize brS9mm/3/8":						"          "
*PageSize brS12mm/1/2":						"          "
*PageSize brS18mm/3/4":						"          "
*PageSize brS24mm/1":						"          "
*PageSize brS36mm/1 1/2":						"          "
*%PageSize brS6X2/6 mm x 2:					"          "
*%PageSize brS9X2/9 mm x 2:					"          "
*%PageSize brS12X2/12 mm x 2:					"          "
*%PageSize brS18X2/3/4" x 2:					"          "
*%PageSize brS24X2/1" x 2:					"          "
*%PageSize brS36X2/1 1/2" x 2:					"          "
*%PageSize brS6X3/6 mm x 3:					"          "
*%PageSize brS9X3/9 mm x 3:					"          "
*%PageSize brS12X3/12 mm x 3:					"          "
*%PageSize brS18X3/3/4" x 3:					"          "
*%PageSize brS24X3/1" x 3:					"          "
*%PageSize brS36X3/1 1/2" x 3:					"          "
*%PageSize brS6X4/6 mm x 4:					"          "
*%PageSize brS9X4/9 mm x 4:					"          "
*%PageSize brS12X4/12 mm x 4:					"          "
*%PageSize brS18X4/3/4" x 4:					"          "
*%PageSize brS24X4/1" x 4:					"          "
*%PageSize brS36X4/1 1/2" x 4:					"          "
*PageSize brSAV1789/AV1789 FILE FOLDER:				"          "
*PageSize brSAV1957/AV1957 RETURN ADDRESS:				"          "
*PageSize brSAV2067/AV2067 ADDRESS:				"          "
*CloseUI: *PageSize

*OpenUI *PageRegion: PickOne
*OrderDependency: 12 AnySetup *PageRegion
*DefaultPageRegion: brS36mm
*PageRegion brS6mm/1/4":						"          "
*PageRegion brS9mm/3/8":						"          "
*PageRegion brS12mm/1/2":						"          "
*PageRegion brS18mm/3/4":						"          "
*PageRegion brS24mm/1":						"          "
*PageRegion brS36mm/1 1/2":						"          "
*%PageRegion brS6X2/6 mm x 2:					"          "
*%PageRegion brS9X2/9 mm x 2:					"          "
*%PageRegion brS12X2/12 mm x 2:					"          "
*%PageRegion brS18X2/3/4" x 2:					"          "
*%PageRegion brS24X2/1" x 2:					"          "
*%PageRegion brS36X2/1 1/2" x 2:					"          "
*%PageRegion brS6X3/6 mm x 3:					"          "
*%PageRegion brS9X3/9 mm x 3:					"          "
*%PageRegion brS12X3/12 mm x 3:					"          "
*%PageRegion brS18X3/3/4" x 3:					"          "
*%PageRegion brS24X3/1" x 3:					"          "
*%PageRegion brS36X3/1 1/2" x 3:					"          "
*%PageRegion brS6X4/6 mm x 4:					"          "
*%PageRegion brS9X4/9 mm x 4:					"          "
*%PageRegion brS12X4/12 mm x 4:					"          "
*%PageRegion brS18X4/3/4" x 4:					"          "
*%PageRegion brS24X4/1" x 4:					"          "
*%PageRegion brS36X4/1 1/2" x 4:					"          "
*PageRegion brSAV1789/AV1789 FILE FOLDER:				"          "
*PageRegion brSAV1957/AV1957 RETURN ADDRESS:			"          "
*PageRegion brSAV2067/AV2067 ADDRESS:				"          "
*CloseUI: *PageRegion

*DefaultImageableArea: brS36mm
*ImageableArea brS6mm/1/4":					"0  2.9 12.8  280.5"
*ImageableArea brS9mm/3/8":					"0  2.9 21.2  280.5"
*ImageableArea brS12mm/1/2":					"0 2.9 30	280.5"
*ImageableArea brS18mm/3/4":					"0 2.9 46.8	280.5"
*ImageableArea brS24mm/1":					"0 2.9 64	280.5"
*ImageableArea brS36mm/1 1/2":					"0 2.9 76.8	280.5"
*%ImageableArea brS6X2/6 mm x 2:					"0  2.9 33.6 280.5"
*%ImageableArea brS9X2/9 mm x 2:					"0  2.9 50.4	280.5"
*%ImageableArea brS12X2/12 mm x 2:				"0  2.9 68	280.5"
*%ImageableArea brS18X2/3/4" x 2:				"0  2.9 101.6	280.5"
*%ImageableArea brS24X2/1" x 2:				"0  2.9 136	280.5"
*%ImageableArea brS36X2/1 1/2" x 2:				"0  2.9 153.06	280.5"
*%ImageableArea brS6X3/6 mm x 3:					"0  2.9 50.4	280.5"
*%ImageableArea brS9X3/9 mm x 3:					"0  2.9 75.6	280.5"
*%ImageableArea brS12X3/12 mm x 3:				"0  2.9 102	280.5"
*%ImageableArea brS18X3/3/4" x 3:				"0  2.9 152.4	280.5"
*%ImageableArea brS24X3/1" x 3:				"0  2.9 204	280.5"
*%ImageableArea brS36X3/1 1/2" x 3:				"0	2.9 230.4	280.5"
*%ImageableArea brS6X4/6 mm x 4:					"0  2.9 67.2	280.5"
*%ImageableArea brS9X4/9 mm x 4:					"0  2.9 100.8	280.5"
*%ImageableArea brS12X4/12 mm x 4:				"0    2.9 136	280.5"
*%ImageableArea brS18X4/3/4" x 4:				"0  2.9 203.2	280.5"
*%ImageableArea brS24X4/1" x 4:				"0    2.9 272	280.5"
*%ImageableArea brS36X4/1 1/2" x 4:				"0 2.9 307.2	280.5"
*ImageableArea brSAV1789/AV1789 FILE FOLDER:			"0  14.4 38.4 238.2"
*ImageableArea brSAV1957/AV1957 RETURN ADDRESS:			"0  14.4 44.8	148"
*ImageableArea brSAV2067/AV2067 ADDRESS:				"0  14.4 48	175.2"



*%==== Information About Media Sizes ========
*DefaultPaperDimension: brS36mm
*PaperDimension brS6mm/1/4":					"12.8  283.4"
*PaperDimension brS9mm/3/8":					"21.2  283.4"
*PaperDimension brS12mm/1/2":					"30    283.4"
*PaperDimension brS18mm/3/4":					"46.8  283.4"
*PaperDimension brS24mm/1":					"64   283.4"
*PaperDimension brS36mm/1 1/2":					"76.8 283.4"
*%PaperDimension brS6X2/6 mm x 2:					"33.6    283.4"
*%PaperDimension brS9X2/9 mm x 2:					"50.4  283.4"
*%PaperDimension brS12X2/12 mm x 2:				"68    283.4"
*%PaperDimension brS18X2/3/4" x 2:				"101.6   283.4"
*%PaperDimension brS24X2/1" x 2:				"136   283.4"
*%PaperDimension brS36X2/1 1/2" x 2:				"153.06 283.4"
*%PaperDimension brS6X3/6 mm x 3:					"50.4  283.4"
*%PaperDimension brS9X3/9 mm x 3:					"75.6  283.4"
*%PaperDimension brS12X3/12 mm x 3:				"102   283.4"
*%PaperDimension brS18X3/3/4" x 3:				"152.4 283.4"
*%PaperDimension brS24X3/1" x 3:				"204   283.4"
*%PaperDimension brS36X3/1 1/2" x 3:				"230.4   283.4"
*%PaperDimension brS6X4/6 mm x 4:					"67.2  283.4"
*%PaperDimension brS9X4/9 mm x 4:					"100.8 283.4"
*%PaperDimension brS12X4/12 mm x 4:				"136   283.4"
*%PaperDimension brS18X4/3/4" x 4:				"203.2 283.4"
*%PaperDimension brS24X4/1" x 4:				"272 283.4"
*%PaperDimension brS36X4/1 1/2" x 4:				"307.2 283.4"
*PaperDimension brSAV1789/AV1789 FILE FOLDER:			"38.4   252.6"
*PaperDimension brSAV1957/AV1957 RETURN ADDRESS:			"44.8  162.4"
*PaperDimension brSAV2067/AV2067 ADDRESS:				"48  189.6"

*%==== Resolution Features =================================
*OpenUI *Resolution/Resolution: PickOne
*OrderDependency: 14 AnySetup *Resolution
*DefaultResolution: Standard
*Resolution	Standard/360 X 360 dpi (Standard): 	"          "
*%Resolution	HGTape/360 X 720dpi (HG Tape): 		"          "
*CloseUI: *Resolution

*%=== Media Type ================================
*%OpenUI *MediaType/Media Type: PickOne
*%OrderDependency: 17 AnySetup *MediaType
*%DefaultMediaType: Plain
*%MediaType Plain/Plain Paper: "          "
*%MediaType Thin/Thin Paper: "          "
*%MediaType Thick/Thick Paper: "          "
*%MediaType Thicker/Thicker Paper: "          "
*%MediaType Transparencies/Transparencies: "          "
*%MediaType Recycled/Recycled Paper: "          "
*%CloseUI: *MediaType

*OpenUI *BrMargin/Margin: PickOne
*OrderDependency: 19 AnySetup  *BrMargin
*DefaultBrMargin: 1
*BrMargin 1/1 mm: ""
*BrMargin 2/2 mm: ""
*BrMargin 3/3 mm: ""
*BrMargin 4/4 mm: ""
*BrMargin 5/5 mm: ""
*BrMargin 6/6 mm: ""
*BrMargin 7/7 mm: ""
*BrMargin 8/8 mm: ""
*BrMargin 9/9 mm: ""
*BrMargin 10/10 mm: ""
*BrMargin 11/11 mm: ""
*BrMargin 12/12 mm: ""
*BrMargin 13/13 mm: ""
*BrMargin 14/14 mm: ""
*BrMargin 15/15 mm: ""
*BrMargin 16/16 mm: ""
*BrMargin 17/17 mm: ""
*BrMargin 18/18 mm: ""
*BrMargin 19/19 mm: ""
*BrMargin 20/20 mm: ""
*BrMargin 21/21 mm: ""
*BrMargin 22/22 mm: ""
*BrMargin 23/23 mm: ""
*BrMargin 24/24 mm: ""
*BrMargin 25/25 mm: ""
*BrMargin 26/26 mm: ""
*BrMargin 27/27 mm: ""
*CloseUI: *BrMargin

*OpenUI *BrAutoTapeCut/Auto Tape Cut: PickOne
*OrderDependency: 20 AnySetup  *BrAutoTapeCut
*DefaultBrAutoTapeCut: OFF
*BrAutoTapeCut OFF/OFF: ""
*BrAutoTapeCut ON/ON: ""
*CloseUI: *BrAutoTapeCut

*OpenUI *BrMirror/Mirror Printing: PickOne
*OrderDependency: 21 AnySetup  *BrMirror
*DefaultBrMirror: OFF
*BrMirror OFF/OFF: ""
*BrMirror ON/ON: ""
*CloseUI: *BrMirror

*OpenUI *BrHalfCut/Multi Half Cut: PickOne
*OrderDependency: 22 AnySetup  * BrHalfCut
*DefaultBrHalfCut: ON
*BrHalfCut OFF/OFF: ""
*BrHalfCut ON/ON: ""
*CloseUI: *BrHalfCut

*OpenUI *BrChain/Chain Printing: PickOne
*OrderDependency: 23 AnySetup  *BrChain
*DefaultBrChain: OFF
*BrChain OFF/OFF: ""
*BrChain ON/ON: ""
*CloseUI: *BrChain

*OpenUI *BrHalftonePattern/Halftone: PickOne
*OrderDependency: 24 AnySetup  *BrHalftonePattern
*DefaultBrHalftonePattern: ErrorDiffusion
*BrHalftonePattern Binary/Binary: ""
*BrHalftonePattern Dither/Dither: ""
*BrHalftonePattern ErrorDiffusion/Error Diffusion: ""
*CloseUI: *BrHalftonePattern

*OpenUI *BrBrightness/Brightness: PickOne
*OrderDependency: 25 AnySetup  *BrBrightness
*DefaultBrBrightness: 0
*BrBrightness 50/50: ""
*BrBrightness 49/49: ""
*BrBrightness 48/48: ""
*BrBrightness 47/47: ""
*BrBrightness 46/46: ""
*BrBrightness 45/45: ""
*BrBrightness 44/44: ""
*BrBrightness 43/43: ""
*BrBrightness 42/42: ""
*BrBrightness 41/41: ""
*BrBrightness 40/40: ""
*BrBrightness 39/39: ""
*BrBrightness 38/38: ""
*BrBrightness 37/37: ""
*BrBrightness 36/36: ""
*BrBrightness 35/35: ""
*BrBrightness 34/34: ""
*BrBrightness 33/33: ""
*BrBrightness 32/32: ""
*BrBrightness 31/31: ""
*BrBrightness 30/30: ""
*BrBrightness 29/29: ""
*BrBrightness 28/28: ""
*BrBrightness 27/27: ""
*BrBrightness 26/26: ""
*BrBrightness 25/25: ""
*BrBrightness 24/24: ""
*BrBrightness 23/23: ""
*BrBrightness 22/22: ""
*BrBrightness 21/21: ""
*BrBrightness 20/20: ""
*BrBrightness 19/19: ""
*BrBrightness 18/18: ""
*BrBrightness 17/17: ""
*BrBrightness 16/16: ""
*BrBrightness 15/15: ""
*BrBrightness 14/14: ""
*BrBrightness 13/13: ""
*BrBrightness 12/12: ""
*BrBrightness 11/11: ""
*BrBrightness 10/10: ""
*BrBrightness 9/9: ""
*BrBrightness 8/8: ""
*BrBrightness 7/7: ""
*BrBrightness 6/6: ""
*BrBrightness 5/5: ""
*BrBrightness 4/4: ""
*BrBrightness 3/3: ""
*BrBrightness 2/2: ""
*BrBrightness 1/1: ""
*BrBrightness 0/0: ""
*BrBrightness -1/-1: ""
*BrBrightness -2/-2: ""
*BrBrightness -3/-3: ""
*BrBrightness -4/-4: ""
*BrBrightness -5/-5: ""
*BrBrightness -6/-6: ""
*BrBrightness -7/-7: ""
*BrBrightness -8/-8: ""
*BrBrightness -9/-9: ""
*BrBrightness -10/-10: ""
*BrBrightness -11/-11: ""
*BrBrightness -12/-12: ""
*BrBrightness -13/-13: ""
*BrBrightness -14/-14: ""
*BrBrightness -15/-15: ""
*BrBrightness -16/-16: ""
*BrBrightness -17/-17: ""
*BrBrightness -18/-18: ""
*BrBrightness -19/-19: ""
*BrBrightness -20/-20: ""
*BrBrightness -21/-21: ""
*BrBrightness -22/-22: ""
*BrBrightness -23/-23: ""
*BrBrightness -24/-24: ""
*BrBrightness -25/-25: ""
*BrBrightness -26/-26: ""
*BrBrightness -27/-27: ""
*BrBrightness -28/-28: ""
*BrBrightness -29/-29: ""
*BrBrightness -30/-30: ""
*BrBrightness -31/-31: ""
*BrBrightness -32/-32: ""
*BrBrightness -33/-33: ""
*BrBrightness -34/-34: ""
*BrBrightness -35/-35: ""
*BrBrightness -36/-36: ""
*BrBrightness -37/-37: ""
*BrBrightness -38/-38: ""
*BrBrightness -39/-39: ""
*BrBrightness -40/-40: ""
*BrBrightness -41/-41: ""
*BrBrightness -42/-42: ""
*BrBrightness -43/-43: ""
*BrBrightness -44/-44: ""
*BrBrightness -45/-45: ""
*BrBrightness -46/-46: ""
*BrBrightness -47/-47: ""
*BrBrightness -48/-48: ""
*BrBrightness -49/-49: ""
*BrBrightness -50/-50: ""
*CloseUI: *BrBrightness

*OpenUI *BrContrast/Contrast: PickOne
*OrderDependency: 26 AnySetup  *BrContrast
*DefaultBrContrast: 0
*BrContrast 50/50: ""
*BrContrast 49/49: ""
*BrContrast 48/48: ""
*BrContrast 47/47: ""
*BrContrast 46/46: ""
*BrContrast 45/45: ""
*BrContrast 44/44: ""
*BrContrast 43/43: ""
*BrContrast 42/42: ""
*BrContrast 41/41: ""
*BrContrast 40/40: ""
*BrContrast 39/39: ""
*BrContrast 38/38: ""
*BrContrast 37/37: ""
*BrContrast 36/36: ""
*BrContrast 35/35: ""
*BrContrast 34/34: ""
*BrContrast 33/33: ""
*BrContrast 32/32: ""
*BrContrast 31/31: ""
*BrContrast 30/30: ""
*BrContrast 29/29: ""
*BrContrast 28/28: ""
*BrContrast 27/27: ""
*BrContrast 26/26: ""
*BrContrast 25/25: ""
*BrContrast 24/24: ""
*BrContrast 23/23: ""
*BrContrast 22/22: ""
*BrContrast 21/21: ""
*BrContrast 20/20: ""
*BrContrast 19/19: ""
*BrContrast 18/18: ""
*BrContrast 17/17: ""
*BrContrast 16/16: ""
*BrContrast 15/15: ""
*BrContrast 14/14: ""
*BrContrast 13/13: ""
*BrContrast 12/12: ""
*BrContrast 11/11: ""
*BrContrast 10/10: ""
*BrContrast 9/9: ""
*BrContrast 8/8: ""
*BrContrast 7/7: ""
*BrContrast 6/6: ""
*BrContrast 5/5: ""
*BrContrast 4/4: ""
*BrContrast 3/3: ""
*BrContrast 2/2: ""
*BrContrast 1/1: ""
*BrContrast 0/0: ""
*BrContrast -1/-1: ""
*BrContrast -2/-2: ""
*BrContrast -3/-3: ""
*BrContrast -4/-4: ""
*BrContrast -5/-5: ""
*BrContrast -6/-6: ""
*BrContrast -7/-7: ""
*BrContrast -8/-8: ""
*BrContrast -9/-9: ""
*BrContrast -10/-10: ""
*BrContrast -11/-11: ""
*BrContrast -12/-12: ""
*BrContrast -13/-13: ""
*BrContrast -14/-14: ""
*BrContrast -15/-15: ""
*BrContrast -16/-16: ""
*BrContrast -17/-17: ""
*BrContrast -18/-18: ""
*BrContrast -19/-19: ""
*BrContrast -20/-20: ""
*BrContrast -21/-21: ""
*BrContrast -22/-22: ""
*BrContrast -23/-23: ""
*BrContrast -24/-24: ""
*BrContrast -25/-25: ""
*BrContrast -26/-26: ""
*BrContrast -27/-27: ""
*BrContrast -28/-28: ""
*BrContrast -29/-29: ""
*BrContrast -30/-30: ""
*BrContrast -31/-31: ""
*BrContrast -32/-32: ""
*BrContrast -33/-33: ""
*BrContrast -34/-34: ""
*BrContrast -35/-35: ""
*BrContrast -36/-36: ""
*BrContrast -37/-37: ""
*BrContrast -38/-38: ""
*BrContrast -39/-39: ""
*BrContrast -40/-40: ""
*BrContrast -41/-41: ""
*BrContrast -42/-42: ""
*BrContrast -43/-43: ""
*BrContrast -44/-44: ""
*BrContrast -45/-45: ""
*BrContrast -46/-46: ""
*BrContrast -47/-47: ""
*BrContrast -48/-48: ""
*BrContrast -49/-49: ""
*BrContrast -50/-50: ""
*CloseUI: *BrContrast

*DefaultFont: Courier
*Font AvantGarde-Book: Standard "(001.006S)" Standard ROM
*Font AvantGarde-BookOblique: Standard "(001.006S)" Standard ROM
*Font AvantGarde-Demi: Standard "(001.007S)" Standard ROM
*Font AvantGarde-DemiOblique: Standard "(001.007S)" Standard ROM
*Font Bookman-Demi: Standard "(001.004S)" Standard ROM
*Font Bookman-DemiItalic: Standard "(001.004S)" Standard ROM
*Font Bookman-Light: Standard "(001.004S)" Standard ROM
*Font Bookman-LightItalic: Standard "(001.004S)" Standard ROM
*Font Courier: Standard "(002.004S)" Standard ROM
*Font Courier-Bold: Standard "(002.004S)" Standard ROM
*Font Courier-BoldOblique: Standard "(002.004S)" Standard ROM
*Font Courier-Oblique: Standard "(002.004S)" Standard ROM
*Font Helvetica: Standard "(001.006S)" Standard ROM
*Font Helvetica-Bold: Standard "(001.007S)" Standard ROM
*Font Helvetica-BoldOblique: Standard "(001.007S)" Standard ROM
*Font Helvetica-Narrow: Standard "(001.006S)" Standard ROM
*Font Helvetica-Narrow-Bold: Standard "(001.007S)" Standard ROM
*Font Helvetica-Narrow-BoldOblique: Standard "(001.007S)" Standard ROM
*Font Helvetica-Narrow-Oblique: Standard "(001.006S)" Standard ROM
*Font Helvetica-Oblique: Standard "(001.006S)" Standard ROM
*Font NewCenturySchlbk-Bold: Standard "(001.009S)" Standard ROM
*Font NewCenturySchlbk-BoldItalic: Standard "(001.007S)" Standard ROM
*Font NewCenturySchlbk-Italic: Standard "(001.006S)" Standard ROM
*Font NewCenturySchlbk-Roman: Standard "(001.007S)" Standard ROM
*Font Palatino-Bold: Standard "(001.005S)" Standard ROM
*Font Palatino-BoldItalic: Standard "(001.005S)" Standard ROM
*Font Palatino-Italic: Standard "(001.005S)" Standard ROM
*Font Palatino-Roman: Standard "(001.005S)" Standard ROM
*Font Times-Bold: Standard "(001.007S)" Standard ROM
*Font Times-BoldItalic: Standard "(001.009S)" Standard ROM
*Font Times-Italic: Standard "(001.007S)" Standard ROM
*Font Times-Roman: Standard "(001.007S)" Standard ROM
*Font ZapfChancery-MediumItalic: Standard "(001.007S)" Standard ROM
*Font ZapfDingbats: Special "(001.004S)" Special ROM
*Font Symbol: Special "(001.007S)" Special ROM
*Font Alaska: Standard "(001.005)" Standard ROM
*Font AlaskaExtrabold: Standard "(001.005)" Standard ROM
*Font AntiqueOakland: Standard "(001.005)" Standard ROM
*Font AntiqueOakland-Bold: Standard "(001.005)" Standard ROM
*Font AntiqueOakland-Oblique: Standard "(001.005)" Standard ROM
*Font ClevelandCondensed: Standard "(001.005)" Standard ROM
*Font Connecticut: Standard "(001.005)" Standard ROM
*Font Guatemala-Antique: Standard "(001.005)" Standard ROM
*Font Guatemala-Bold: Standard "(001.005)" Standard ROM
*Font Guatemala-Italic: Standard "(001.005)" Standard ROM
*Font Guatemala-BoldItalic: Standard "(001.005)" Standard ROM
*Font LetterGothic: Standard "(001.005)" Standard ROM
*Font LetterGothic-Bold: Standard "(001.005)" Standard ROM
*Font LetterGothic-Oblique: Standard "(001.005)" Standard ROM
*Font Maryland: Standard "(001.005)" Standard ROM
*Font Oklahoma: Standard "(001.005)" Standard ROM
*Font Oklahoma-Bold: Standard "(001.005)" Standard ROM
*Font Oklahoma-Oblique: Standard "(001.005)" Standard ROM
*Font Oklahoma-BoldOblique: Standard "(001.005)" Standard ROM
*Font Utah: Standard "(001.005)" Standard ROM
*Font Utah-Bold: Standard "(001.005)" Standard ROM
*Font Utah-Oblique: Standard "(001.005)" Standard ROM
*Font Utah-BoldOblique: Standard "(001.005)" Standard ROM
*Font UtahCondensed: Standard "(001.005)" Standard ROM
*Font UtahCondensed-Bold: Standard "(001.005)" Standard ROM
*Font UtahCondensed-Oblique: Standard "(001.004)" Standard ROM
*Font UtahCondensed-BoldOblique: Standard "(001.005)" Standard ROM
*Font BermudaScript: Standard "(001.005)" Standard ROM
*Font Germany: Standard "(001.005)" Standard ROM
*Font SanDiego: Standard "(001.005)" Standard ROM
*Font US-Roman: Standard "(001.005)" Standard ROM



ENDOFPPDFILE

brotherlpdwrapper=/usr/lib/cups/filter/brlpdwrapperpt9500pc
brotherlpdwrapper64=/usr/lib64/cups/filter/brlpdwrapperpt9500pc
#brotherlpdwrapper=/usr/lib/cups/backend/brusb_pt9500pc
#brotherlpdwrapper64=/usr/lib64/cups/backend/brusb_pt9500pc

rm -f  $brotherlpdwrapper
#echo 'rm -f /usr/lib/cups/filter/brlpdwrapperpt9500pc'


cat <<!ENDOFWFILTER! >$brotherlpdwrapper
#! /bin/sh
#
# Brother Print filter  >>  /usr/lib/cups/backend/brusb_pt9500pc
# Copyright (C) 2005-2006 Brother. Industries, Ltd.
#                                    Ver1.10

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
#

LOGFILE="/dev/null"
LOGLEVEL="1"
LOGCLEVEL="7"
DEBUG=0
NUPENABLE=1
LOG_LATESTONLY=1
errorcode=0

if [ \$DEBUG != 0 ]; then
    LOGFILE=/tmp/br_cupsfilter_debug_log
fi

PPDC=\`printenv | grep "PPD="\`
PPDC=\`echo \$PPDC | sed -e 's/PPD=//'\`

if [ "\$PPDC" = "" ]; then
    PPDC="/usr/share/cups/model/brpt9500pc.ppd"
fi


if [ \$LOGFILE != "/dev/null" ]; then
  if [ \$LOG_LATESTONLY == "1" ]; then
    rm -f \$LOGFILE
    date                                                           >\$LOGFILE
  else
    if [ -e \$LOGFILE ]; then
	    date                                                        >>\$LOGFILE
    else
	    date                                                        >\$LOGFILE
    fi
  fi
    echo "arg0 = \$0"                                           >>\$LOGFILE
    echo "arg1 = \$1"                                           >>\$LOGFILE
    echo "arg2 = \$2"                                           >>\$LOGFILE
    echo "arg3 = \$3"                                           >>\$LOGFILE
    echo "arg4 = \$4"                                           >>\$LOGFILE
    echo "arg5 = \$5"                                           >>\$LOGFILE
    echo "arg6 = \$6"                                           >>\$LOGFILE
    echo "PPD  = \$PPD"                                         >>\$LOGFILE
fi

INPUT_TEMP_PS=\`mktemp /tmp/br_input_ps.XXXXXX\`

nup="cat"
if [ "`echo \$5 | grep 'Nup='`" != '' ] && [ \$NUPENABLE != 0 ]; then

	if   [ "`echo \$5 | grep 'Nup=64'`" != '' ]; then
		nup="psnup -64"
	elif [ "`echo \$5 | grep 'Nup=32'`" != '' ]; then
		nup="psnup -32"
	elif [ "`echo \$5 | grep 'Nup=25'`" != '' ]; then
		nup="psnup -25"
	elif [ "`echo \$5 | grep 'Nup=16'`" != '' ]; then
		nup="psnup -16"
	elif [ "`echo \$5 | grep 'Nup=8'`" != '' ]; then
		nup="psnup -8"
	elif [ "`echo \$5 | grep 'Nup=6'`" != '' ]; then
		nup="psnup -6"
	elif [ "`echo \$5 | grep 'Nup=4'`" != '' ]; then
		nup="psnup -4"
	elif [ "`echo \$5 | grep 'Nup=2'`" != '' ]; then
		nup="psnup -2"
	elif [ "`echo \$5 | grep 'Nup=1'`" != '' ]; then
		nup="cat"
	fi
	echo   "NUP=\$nup"                                      >>\$LOGFILE
   if [ -e /usr/bin/psnup ]; then
       if [ \$# -ge 7 ]; then
	       cat \$6  | \$nup > \$INPUT_TEMP_PS
       else
	       cat       | \$nup > \$INPUT_TEMP_PS
       fi
   else
       if [ \$# -ge 7 ]; then
	       cp \$6  \$INPUT_TEMP_PS
       else
	       cat    > \$INPUT_TEMP_PS
       fi
   fi
else
   if [ \$# -ge 7 ]; then
      cp \$6  \$INPUT_TEMP_PS
   else
      cat    > \$INPUT_TEMP_PS
   fi
fi
if [ -e "/usr/local/Brother/PTouch/pt9500pc/lpd/filterpt9500pc" ]; then
       :
else
    echo "ERROR: /usr/local/Brother/PTouch/pt9500pc/lpd/filterpt9500pc does not exist"   >>\$LOGFILE
    errorcode=30
    exit
fi

CUPSOPTION=\`echo "\$5 Copies=\$4" | sed -e 's/BrChain/Chain/' -e 's/BrBrightness/Brightness/' -e 's/BrContrast/Contrast/' -e 's/BrHalfCut/HalfCut/' -e 's/BrAutoTapeCut/AutoCut/' -e 's/BrMirror/Mirror/' -e 's/BrHalftonePattern/Halftone/' -e 's/Binary/Binary/' -e 's/Dither/Dither/' -e 's/ErrorDiffusion/ErrorDiffusion/' -e 's/PageSize/media/'  -e 's/multiple-document-handling/Collate/' -e 's/separate-documents-collated-copies/ON/' -e 's/separate-documents-uncollated-copies/OFF/'\`
if [ -e "/usr/local/Brother/PTouch/pt9500pc/cupswrapper/brcupsconfpt1" ]; then
  if [ \$DEBUG = 0 ]; then
     /usr/local/Brother/PTouch/pt9500pc/cupswrapper/brcupsconfpt1  pt9500pc  \$PPDC 0 "\$CUPSOPTION" >> /dev/null
  else
     /usr/local/Brother/PTouch/pt9500pc/cupswrapper/brcupsconfpt1  pt9500pc  \$PPDC \$LOGCLEVEL "\$CUPSOPTION" >>\$LOGFILE
  fi
fi

if [ \$DEBUG -lt 10 ]; then
    cat    \$INPUT_TEMP_PS | /usr/local/Brother/PTouch/pt9500pc/lpd/filterpt9500pc "\$\$" "CUPS" "USB"

    if [ \$LOGLEVEL -gt 2 ];  then
	   if [ \$LOGFILE != "/dev/null" ]; then
	     echo ""                                                >>\$LOGFILE
	     echo "    ------PostScript Data-------"                >>\$LOGFILE
	     cat    \$INPUT_TEMP_PS                                  >>\$LOGFILE
	   fi
    fi
fi
rm -f  \$INPUT_TEMP_PS

exit $errorcode

!ENDOFWFILTER!

chmod a+x $brotherlpdwrapper
if [ -e /usr/lib64/cups/backend ]; then
   cp $brotherlpdwrapper  $brotherlpdwrapper64
fi

chmod a+w /usr/local/Brother/PTouch/pt9500pc/inf/brpt9500pcrc
chmod a+w /usr/local/Brother/PTouch/pt9500pc/inf
if [ -e /etc/init.d/lpd ]; then
   /etc/init.d/lpd stop
fi
if [  -e /etc/init.d/lprng ]; then
   /etc/init.d/lprng stop
fi

ln -sf /usr/local/Brother/PTouch/pt9500pc/lpd/brusb_pt9500pc /usr/lib/cups/backend/brusb_pt9500pc


if [  -e /etc/init.d/cups ]; then
   /etc/init.d/cups restart
elif [  -e /etc/init.d/cupsys ]; then
   /etc/init.d/cupsys restart
fi

sleep 2s

lpadmin -p PT-9500PC -E -v brusb_pt9500pc:/dev/usb -m brpt9500pc.ppd


exit 0

