#! /bin/sh
#
# Copyright (C) 2003-2011 Brother. Industries, Ltd.



PAPER_INF=$1
RC_FILE=$2
FUNC_FILE=`echo $RC_FILE | sed s/rc$/func/`

# get Paper Type
PAPER_TYPE=`sed -n '/PaperType/p' $RC_FILE`
PAPER_TYPE=`echo $PAPER_TYPE | sed -e 's/ //g' -e 's/PaperType=//'`

# get Resolution
RESOLUTION=`sed -n '/Resolution/p' $RC_FILE`
RESOLUTION=`echo $RESOLUTION | sed -e 's/ //g' -e 's/Resolution=//'`

# get paper size
LINE=`eval sed -n '/^"$PAPER_TYPE"/p' $PAPER_INF`
WIDTH=$LINE
HEIGHT=$LINE

WIDTH=`echo $WIDTH | sed -e 's/^.*:[ ]//' -e 's/[ ].*//'`
HEIGHT=`echo $HEIGHT | sed -e 's/^.*[ ]//'`

PRINTABLEAREA=`sed -n '/PrintableArea/p' $RC_FILE`
PRINTABLEAREA=`echo $PRINTABLEAREA | sed -e 's/ //g' -e 's/PrintableArea=//'`

#---
PSTOPS='/usr/sbin/pstops'
if ! [ -f $PSTOPS ];then
  PSTOPS=`grep 'pstops=' $FUNC_FILE | head -1 | sed s/'pstops='//`
fi

#---


shift_x_point=18     		# 150 * 72 / 600
shift_y_point=12     		# 100 * 72 / 600
printablearea_x_point=`expr   $WIDTH \* 72 / 600  - 36`
printablearea_y_point=`expr  $HEIGHT \* 72 / 600  - 24`
case "$RESOLUTION" in
	"300" )
		WIDTH=`expr $WIDTH / 2`
		HEIGHT=`expr $HEIGHT / 2`
		WIDTH_P=`expr $WIDTH - 150`
		HEIGHT_P=`expr $HEIGHT - 100`
		;;
	"600" )
		WIDTH_P=`expr $WIDTH - 300`
		HEIGHT_P=`expr $HEIGHT - 200`
		;;
	"1200" | "1200A" | "HQ1200A" | "1200B" | "HQ1200B" )
		RESOLUTION=1200
		WIDTH=`expr $WIDTH \* 2`
		HEIGHT=`expr $HEIGHT \* 2`
		WIDTH_P=`expr $WIDTH - 600`
		HEIGHT_P=`expr $HEIGHT - 400`		
		;;
esac






GHOST_SCRIPT=`which gs`
OUTPUT_TYPE=bit
GHOST_OPT="-q -dNOPROMPT -dNOPAUSE -dSAFER -sDEVICE=$OUTPUT_TYPE -sstdout=%stderr -sOutputFile=- - -c quit"

exec $GHOST_SCRIPT -r$RESOLUTION -g${WIDTH}x${HEIGHT} $GHOST_OPT 


